---
version: '3'
services:
  healthcheck:
    image: reireias/mysql-healthcheck
    ports:
      - 8080:8080
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_QUERY: 'show databases;'
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      ADDRESS: 0.0.0.0:8080
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
